### PR TITLE
Revert inert & bump deps

### PR DESCRIPTION
**Pull request by iamdarkle**
As I discussed privately with @davwheat, it has spontaneously stopped working MediaEmbed content (you can't interact for example with iframes of MP4 videos, Youtube, Twitter...) with rich content enabled, it seems that `inert` has been recently implemented in Chrome and that's why it has stopped working in multiple browsers (tested in Chrome and Edge), this PR removes it so that MediaEmbed content is usable again.

### CODE REVIEW

**Comment by iamdarkle** [comment]
Hey @imorland sorry to bother you, but did you get a chance to take a look at this?

**Comment by imorland** [comment]
Hey @iamdarkle sorry for the long delay.

I do understand where you are coming from here, and initially it does make sense to remove `inert` . Something in the back of my head tells me there was another reason for adding this, which escapes me at the moment. Let me have a think..

**Comment by iamdarkle** [comment]
I think davwheat implemented it a while ago and it really is the modern way to avoid using `pointer-events: none;` and therefore it would be the right thing to do, but I honestly can't understand why Chrome has implemented the `inert` in this way without excluding iframes (as it does `pointer-events: none;`), I think in general it's something that is going to prevent its use...

**Comment by imorland** [comment]
I've been thinking about this a little. I believe the best course of action will be to merge this so that the extension is usable on Chome again for now, whilst an alternative is considered.

Thanks for putting this PR together, I'll get this merged shortly

**Comment by imorland** [comment]
Released as `1.2.1`, thanks again :)

**Pull request merged**
